# Generated by Django 4.2.7 on 2025-11-19 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', models.TextField()),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('published', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0, help_text='Order for displaying in navigation')),
                ('show_in_navigation', models.BooleanField(default=True, help_text='Show this page in navigation menu')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['slug'], name='pages_page_slug_3e99a9_idx'), models.Index(fields=['published'], name='pages_page_publish_fd6605_idx'), models.Index(fields=['order'], name='pages_page_order_fbfddd_idx')],
            },
        ),
    ]
